receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        
processors:
  batch:
    send_batch_size: 1000
    send_batch_max_size: 1000
    timeout: 10s

exporters:
  debug:
    verbosity: detailed
  file:
    path: ./data/traces.json
  cassandra:
    dsn: 127.0.0.1

extensions:
  health_check:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, cassandra]