receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        
processors:
  batch:
  
exporters:
  debug:
    verbosity: detailed
  cassandra:
    dsn: scylla
    port: 9042
    trace_table: "spans"
    compression:
      sstable_compression: true
      algorithm: "LZ4Compressor"

extensions:
  health_check:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, cassandra]